on:
  push:
    branches:
      - main

name: Build and Deploy
env:
  REACT_APP_API_BASE_URL: http://ec2-18-204-215-89.compute-1.amazonaws.com/api
jobs:
  build:
    runs-on: drivent-front
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run
        run: docker-compose down && docker-compose up --build -d
